name: Deploy to Local Raspbi via cloudflare tunnel

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - name: SSH-Schlüssel einrichten
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /tmp/private_key
          rm /tmp/private_key

      - name: Host-Key zum known_hosts hinzufügen
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H alau.at >> ~/.ssh/known_hosts

      - name: Gebaute Dateien auf Raspberry Pi übertragen
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          rsync -avz --delete ./build/ andreas@alau.at:/var/www/sveltekit/

      - name: Docker Compose auf dem Raspberry Pi ausführen
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh andreas@alau.at 'cd ~/cloudflare && sudo docker compose --env-file=../cloudflare/cloudflare.env up -d --build'
