name: Deploy to Local Raspbi via cloudflare tunnel

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      #install cloudflare warp client
      - name: Install Cloudflare Warp Client
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ focal main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update
          sudo apt-get update && sudo apt-get install -y --no-install-recommends cloudflare-warp

      #add mdm.xml file to warp client directory
      - name: Add mdm.xml file
        run: |
          sudo mkdir -p /var/lib/cloudflare-warp
          sudo tee /var/lib/cloudflare-warp/mdm.xml > /dev/null <<EOF
          <dict>
            <key>organisation</key>
            <string>lauhard</string>
            <key>auth_client_id</key>
            <string>8127475c081dda84e13368ea3d4178b6.access</string>
            <key>auth_client_secret</key>
            <string>77c95a445a49d2885ac6db54df624e5245e6fd54052a62c9f565772ec9962cc5</string>
            <key>organization</key>
            <string>lauhard</string>
            <key>onboarding</key>
            <false/>
            <!-- Additional configuration parameters can be added here -->
          </dict>
          EOF

      - name: Check mdm.xml
        run: sudo cat /var/lib/cloudflare-warp/mdm.xml

      # Connect to Cloudflare Warp
      - name: Connect to Cloudflare
        run: |
          set -e
          sudo warp-cli --accept-tos connect
          sleep 5
          sudo warp-cli --accept-tos status

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH Verbindung erfolgreich'"
